### ISSUE TITLE
How to let the timetable has rounded corner?

### ISSUE THREAD

**Issue by PallonCX** [PallonCX/nus-class-connect#2]
For now, our timetable looks like this:
<img width="1418" alt="Screenshot 2024-02-20 at 11 55 36 PM" src="https://github.com/PallonCX/nus-class-connect/assets/102943362/8be8dcbf-45b1-4bb1-a8ac-1e08474629f0">

I'm trying to let it have rounded corner like this:
<img width="839" alt="Screenshot 2024-02-20 at 11 56 58 PM" src="https://github.com/PallonCX/nus-class-connect/assets/102943362/f849ad74-afe8-4b33-b26a-73f972067d8b">

How should I do that? The codes that creates the timetable is in `Timetable.js`, together with its style file `Timetable.css`.

Feel free to share with me ways to solve this, or fix this yourself (then make a pull request for us to merge)!

**Comment by ShenyiCui** [comment]
![image](https://github.com/PallonCX/nus-class-connect/assets/29945147/d4ab7b59-5b2e-47c0-8668-5204d26f17a4)

Timetable.css
```css
.Timetable-frame {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-top: 20px;
}

.Timetable {
  width: 100%; /* Set timetable width to 100% */
}

.Timetable table {
  width: 100%;
  border-spacing: 0;
}

.Timetable th,
td {
  border: 1px solid #ddd;
  padding: 8px;
  text-align: center;
}

.Timetable th {
  background-color: #f2f2f2;
}

.Timetable table tr:last-child td:first-child {
  border-bottom-left-radius: 10px;
}

.Timetable table tr:last-child td:last-child {
  border-bottom-right-radius: 10px;
}

.Timetable table thead tr th:first-child {
  border-top-left-radius: 10px;
}

.Timetable table thead tr th:last-child {
  border-top-right-radius: 10px;
}

```
